In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("Combined_dataset.csv")

In [18]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [20]:
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [21]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [22]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [23]:
df = df.dropna()

In [25]:
df = df.drop_duplicates()

In [33]:
high_rating = df[df["rating"] > 1]
high_rating.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
418,18689340,Flying Machine,Women Black Wide Leg High-Rise Light Fade Crop...,4.3,36,2349,42.0,"""₹1,362.00""",INR,http://assets.myntassets.com/assets/images/186...,...,ARV███ LI███TYL█████████LIM██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-18689340_cae700""]",10T███LOO███DU █████████ITY███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,1,"""₹1,362.00"""
752,18241626,Roadster,The Lifestyle Co. Women Maroon & Black Ribbed...,4.5,25,1699,62.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Tru███t C███erc███,"[{""size"":""XS"",""value"":""36.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹645.00"""
753,18241400,Roadster,Women Black & White Geometric Pullover Sweater,3.8,57,2699,5.0,"""₹944.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Tru███t C███erc███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""B...","[""rw-18241400_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹944.00"""
754,18241644,Roadster,The Lifestyle Co. Women Pink Acrylic Pullover,4.3,55,1999,62.0,"""₹759.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Tru███t C███erc███,"[{""size"":""XS"",""value"":""38.0in"",""value_name"":""B...","[""rw-18241644_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹759.00"""
755,18240570,all about you,Women Navy Blue & Red Checked Pullover,4.3,53,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18240570_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters,1,"""₹874.00"""

# Quantity column was not available in dataset,
# so a default quantity value of 1 was used.

In [34]:
df["quantity"] = 1
df["total_amount"] = df["final_price"] * df["quantity"]

In [35]:
df.groupby("category")["rating"].mean()

category
jeans       4.300
sweaters    4.275
tops        3.900
Name: rating, dtype: float64

In [39]:
df.to_csv("cleaned_dataset.csv", index=False)

# Summary

1. Loaded ecommerce dataset using Pandas
2. Explored dataset using head(), info(), describe()
3. Checked missing values
4. Removed null values
5. Removed duplicate rows
6. Filtered highly rated products
7. Created derived column total_amount
8. Saved cleaned dataset as cleaned_dataset.csv