In [23]:
import pandas as pd

In [24]:
df = pd.read_csv("Combined_dataset.csv")

In [27]:
df.shape

(1000, 24)

In [41]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No feedback,Unknown,"[{""size"":""Onesize""}]",[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No feedback,Unknown,"[{""size"":""Onesize""}]","[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No feedback,Unknown,"[{""size"":""S""}]","[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No feedback,Unknown,"[{""size"":""Onesize""}]",No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No feedback,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [42]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No feedback,Unknown,"[{""size"":""Onesize""}]",No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No feedback,Unknown,"[{""size"":""Onesize""}]",No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Dial Material"",""specif...","{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No feedback,Unknown,"[{""size"":""Onesize""}]","[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No feedback,Tru███m R███il,"[{""size"":""Onesize""}]",No variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Mat Thickness"",""specif...","{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",No feedback,Unknown,"[{""size"":""Medium""}]","[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [6]:
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [7]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [32]:
# checking which columns have null values
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [47]:
df['discount'] = df['discount'].fillna(df['discount'].median())

df['what_customers_said'] = df['what_customers_said'].fillna('No feedback')

df['seller_name'] = df['seller_name'].fillna('Unknown Seller')

df['variations'] = df['variations'].fillna('No Variations')
print(df.isnull().sum())

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [50]:
df['final_price'] = df['final_price'].astype(str)

df['final_price'] = df['final_price'].str.replace('₹', '', regex=False)

df['final_price'] = df['final_price'].str.replace(',', '', regex=False)

df['final_price'] = df['final_price'].str.replace('"', '', regex=False)

# convert to numeric

df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

# Verify datatype
df['final_price'].dtype

dtype('float64')

In [53]:
print("Before:", len(df))

df = df.drop_duplicates()

print("After:", len(df))

print("Duplicate rows:", df.duplicated().sum())

Before: 1000
After: 1000
Duplicate rows: 0

In [36]:
high_rating = df[df["rating"] > 4]
high_rating.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No feedback,Unknown,"[{""size"":""Onesize""}]","[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No feedback,Unknown,"[{""size"":""S""}]","[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No feedback,Unknown,"[{""size"":""Onesize""}]",No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No feedback,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,56.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Finish"",""specification...","{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",No feedback,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]","[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories

In [55]:
# Finding Total Amount
df["quantity"] = 1
df["total_amount"] = df["final_price"] * df["quantity"]

# Discount
df['discount_amount'] = df['initial_price'] - df['final_price']

#Show
df[['initial_price',
    'final_price',
    'quantity',
    'discount_amount',
    'total_amount']].head(10)

   initial_price  final_price  quantity  discount_amount  total_amount
0           3995       3995.0         1              0.0        3995.0
1           2899       2899.0         1              0.0        2899.0
2           2999       2999.0         1              0.0        2999.0
3           1675       1675.0         1              0.0        1675.0
4           2899       2899.0         1              0.0        2899.0
5           1399       1399.0         1              0.0        1399.0
6           1399       1399.0         1              0.0        1399.0
7           2999       2999.0         1              0.0        2999.0
8           2999       2999.0         1              0.0        2999.0
9           2199       2199.0         1              0.0        2199.0

In [60]:
seller_products = df.groupby('seller_name')['product_id'].count().sort_values(ascending=False)

seller_products.head(10)

seller_name
Unknown         301
Supom            40
Vis St           29
Flatarmme        27
ARV LITYLLIM     26
Wesry dind_M     21
Trut Cerc        16
Trum Ril         15
IND NEE PMIT     13
AARLIFYLELIM     13
Name: product_id, dtype: int64

In [61]:
category_discount = df.groupby('category')['discount'].mean().sort_values(ascending=False)

category_discount.head(10)

category
trolley-bag    85.000000
wall-art       84.000000
belts          84.000000
ring           79.000000
clutches       75.000000
kurtis         75.000000
showpieces     75.000000
boots          74.000000
sarees         73.181818
towel-set      70.000000
Name: discount, dtype: float64

In [58]:
# clean text columns

text_columns = ['seller_name', 'category']

for col in text_columns:
    df[col] = (
        df[col]
        .astype(str)
        .str.encode('ascii', 'ignore')
        .str.decode('ascii')
        .str.strip()
    )

print("Text columns cleaned successfully")

Text columns cleaned successfully

In [67]:
df.to_csv('cleaned_dataset.csv', index=False)
print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully

In [64]:
df.shape

(1000, 25)

In [66]:
cleaned_df = pd.read_csv('cleaned_dataset.csv')

cleaned_df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,variations,best_offer,more_offers,category,quantity,total_amount,discount_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,No feedback,Unknown,"[{""size"":""Onesize""}]",[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,3995.0,0.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,No feedback,Unknown,"[{""size"":""Onesize""}]","[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,2899.0,0.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,No feedback,Unknown,"[{""size"":""S""}]","[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,2999.0,0.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,No feedback,Unknown,"[{""size"":""Onesize""}]",No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,1675.0,0.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,No feedback,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,1,2899.0,0.0

In [ ]:
# Summary

1. Loaded ecommerce dataset using Pandas
2. Explored dataset using head(), tail(), info(), describe()
3. Checked missing values
4. Removed unnecessary columns
5. Filled missing values using suitable techniques
6. Cleaned and converted price columns into numeric format
7. Analyzed duplicate rows
8. Removed duplicate records
9. Created derived columns:
   - quantity
   - total_amount
   - discount_amount
10. Applied filtering operations
11. Performed professional groupby analysis
12. Generated business insights
13. Saved cleaned dataset as cleaned_dataset.csv